#!/usr/bin/env bash

sam3_setup__prompt_value() {
  local prompt="$1"
  local default_value="${2-}"
  local secret="${3:-0}"
  local value=""

  if [ -t 0 ]; then
    if [ -n "$default_value" ]; then
      printf "%s [%s]: " "$prompt" "$default_value" >&2
    else
      printf "%s: " "$prompt" >&2
    fi
    if [ "$secret" = "1" ]; then
      IFS= read -r -s value
      printf "\n" >&2
    else
      IFS= read -r value
    fi
  fi

  if [ -z "$value" ]; then
    value="$default_value"
  fi

  printf "%s\n" "$value"
}

sam3_setup__download_file() {
  local url="$1"
  local output_path="$2"
  local label="$3"
  local hf_token="$4"
  local temp_path="${output_path}.part"

  if [ -s "$output_path" ]; then
    printf "Reusing existing %s: %s\n" "$label" "$output_path" >&2
    return 0
  fi

  printf "Downloading %s to %s\n" "$label" "$output_path" >&2
  if ! curl \
    --fail \
    --show-error \
    --location \
    --continue-at - \
    --header "Authorization: Bearer ${hf_token}" \
    --output "$temp_path" \
    "$url"
  then
    printf "Download failed for %s\n" "$label" >&2
    return 1
  fi

  mv "$temp_path" "$output_path"
}

sam3_setup__write_env_file() {
  local env_file="$1"
  {
    printf "# Generated by examples/sam3/setup_sam3_env.sh\n"
    printf "export SAM3_CHECKPOINT_DIR=%q\n" "$SAM3_CHECKPOINT_DIR"
    printf "export SAM3_CHECKPOINT=%q\n" "$SAM3_CHECKPOINT"
    printf "export SAM3_TOKENIZER=%q\n" "$SAM3_TOKENIZER"
    printf "export SAM3_TEST_CHECKPOINT_DIR=%q\n" "$SAM3_TEST_CHECKPOINT_DIR"
    printf "export SAM3_TEST_CHECKPOINT=%q\n" "$SAM3_TEST_CHECKPOINT"
  } > "$env_file"
}

sam3_setup__main() {
  local default_dir="${PWD}/chkpts"
  local repo_id="${SAM3_DOWNLOAD_REPO_ID:-facebook/sam3}"
  local revision="${SAM3_DOWNLOAD_REVISION:-main}"
  local hf_username="${HF_USERNAME:-${HUGGINGFACE_USERNAME:-}}"
  local hf_token="${HF_TOKEN:-${HUGGING_FACE_HUB_TOKEN:-${HUGGINGFACE_HUB_TOKEN:-}}}"
  local download_dir_input="${SAM3_DOWNLOAD_DIR:-}"
  local download_dir=""
  local checkpoint_url=""
  local tokenizer_url=""
  local env_file=""

  if ! command -v curl >/dev/null 2>&1; then
    printf "This helper requires curl.\n" >&2
    return 1
  fi

  printf "This helper downloads the gated %s checkpoint and tokenizer.\n" "$repo_id" >&2
  printf "Make sure your Hugging Face account already has access to the model.\n" >&2

  if [ -z "$hf_username" ]; then
    hf_username="$(sam3_setup__prompt_value "Hugging Face username" "")"
  fi
  if [ -z "$hf_username" ]; then
    printf "A Hugging Face username is required.\n" >&2
    return 1
  fi

  if [ -z "$hf_token" ]; then
    hf_token="$(sam3_setup__prompt_value "Hugging Face access token" "" "1")"
  fi
  if [ -z "$hf_token" ]; then
    printf "A Hugging Face access token is required.\n" >&2
    return 1
  fi

  if [ -z "$download_dir_input" ]; then
    download_dir_input="$(sam3_setup__prompt_value "Download directory" "$default_dir")"
  fi
  if [ -z "$download_dir_input" ]; then
    download_dir_input="$default_dir"
  fi

  download_dir_input="${download_dir_input/#\~/$HOME}"
  mkdir -p "$download_dir_input" || return 1
  download_dir="$(cd "$download_dir_input" && pwd -P)"

  checkpoint_url="https://huggingface.co/${repo_id}/resolve/${revision}/sam3.pt"
  tokenizer_url="https://huggingface.co/${repo_id}/resolve/${revision}/tokenizer.json"

  sam3_setup__download_file "$checkpoint_url" "$download_dir/sam3.pt" "sam3.pt" "$hf_token" || return 1
  sam3_setup__download_file "$tokenizer_url" "$download_dir/tokenizer.json" "tokenizer.json" "$hf_token" || return 1

  export SAM3_CHECKPOINT_DIR="$download_dir"
  export SAM3_CHECKPOINT="$download_dir/sam3.pt"
  export SAM3_TOKENIZER="$download_dir/tokenizer.json"
  export SAM3_TEST_CHECKPOINT_DIR="$download_dir"
  export SAM3_TEST_CHECKPOINT="$download_dir/sam3.pt"

  env_file="$download_dir/sam3-paths.env"
  sam3_setup__write_env_file "$env_file" || return 1

  printf "Downloaded SAM3 assets for %s into %s\n" "$hf_username" "$download_dir" >&2
  if [ "${BASH_SOURCE[0]}" != "$0" ]; then
    printf "Exported SAM3_CHECKPOINT_DIR, SAM3_CHECKPOINT, SAM3_TOKENIZER, SAM3_TEST_CHECKPOINT_DIR, and SAM3_TEST_CHECKPOINT in the current shell.\n" >&2
  else
    printf "Wrote reusable exports to %s\n" "$env_file" >&2
    printf "Load them into your current shell with:\n" >&2
    printf "  source %q\n" "$env_file" >&2
  fi
}

sam3_setup__main "$@"
sam3_setup__status=$?

unset -f sam3_setup__prompt_value
unset -f sam3_setup__download_file
unset -f sam3_setup__write_env_file
unset -f sam3_setup__main

if [ "${BASH_SOURCE[0]}" != "$0" ]; then
  return "$sam3_setup__status"
fi
exit "$sam3_setup__status"
